description = "\u001b[1;36mtermshark\u001b[22;39m: WireShark in the terminal"

[[recipes]]
names = ["build", "b"]
description = "\u001b[4mB\u001b[24muild release binary"
arguments = []
command = ["cargo", "build", "--release", "--features=cli"]

[[recipes]]
names = ["dev", "d"]
description = "Build \u001b[4md\u001b[24ev binary"
arguments = []
command = ["cargo", "build", "--features=cli"]

[[recipes]]
names = ["run", "r"]
description = "Compile and \u001b[4mr\u001b[24mun"
arguments = ["*rest"]
command = ["cargo", "run", "--features=cli", "--", ["*rest"]]

[[recipes]]
names = ["test", "t"]
description = "Run \u001b[4mt\u001b[24mests"
arguments = ["*rest"]
command = ["cargo", "test", ["*rest"]]

[[recipes]]
names = ["version", "v"]
description = "Set or get \u001b[4mv\u001b[24mersion"
arguments = ["?version"]
command = ["./scripts/version.sh", ["?version"]]
