[package]
name = "sniffer"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "My traffic sniffer for the course \"Software and System Security\""
keywords = ["sniffer", "pcap", "network", "traffic"]
categories = ["network-programming", "command-line-utilities"]
include = ["src", "README.md", "LICENSE"]
repository = "https://github.com/PRO-2684/sniffer"
license = "MIT"
authors = ["PRO-2684"]

[dependencies]
argh = { version = "0.1.13", optional = true, default-features = false, features = [
    "help",
] }
chrono = { version = "0.4.42", default-features = false, features = [
    "alloc",
    "std",
] }
crossterm = { version = "0.29.0", optional = true }
num_enum = "0.7.4"
pcap = "2.3.0"
ratatui = { version = "0.29.0", optional = true }

[[bin]]
name = "sniffer"
required-features = ["cli"]

[features]
cli = ["argh", "crossterm", "ratatui"]

[profile.release]
debug = false     # Disable debug information in release builds.
strip = true      # Automatically strip symbols from the binary.
lto = true        # Enable link-time optimization.
codegen-units = 1 # Set the number of codegen units to 1.

[dev-dependencies]
libc = "0.2.176"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install"]

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
